#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Basics of CRUD
#### Create, Read, Update, and Delete

# CREATE

In [6]:
%%sql

USE dog_world;

CREATE TABLE cats (
    cat_id INT AUTO_INCREMENT,
    name VARCHAR(100),
    breed VARCHAR(100),
    age INT,
    PRIMARY KEY (cat_id)
);

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

INSERT INTO cats(name, breed, age) 
VALUES ('Ringo', 'Tabby', 4),
       ('Cindy', 'Maine Coon', 10),
       ('Dumbledore', 'Maine Coon', 11),
       ('Egg', 'Persian', 4),
       ('Misty', 'Tabby', 13),
       ('George Michael', 'Ragdoll', 9),
       ('Jackson', 'Sphynx', 7);

Empty DataFrame
Columns: []
Index: []

# READ

In [9]:
%%sql

SELECT *
FROM cats

   cat_id            name       breed  age
0       1           Ringo       Tabby    4
1       2           Cindy  Maine Coon   10
2       3      Dumbledore  Maine Coon   11
3       4             Egg     Persian    4
4       5           Misty       Tabby   13
5       6  George Michael     Ragdoll    9
6       7         Jackson      Sphynx    7

In [10]:
%%sql

SELECT
    name,
    breed
FROM cats

             name       breed
0           Ringo       Tabby
1           Cindy  Maine Coon
2      Dumbledore  Maine Coon
3             Egg     Persian
4           Misty       Tabby
5  George Michael     Ragdoll
6         Jackson      Sphynx

In [12]:
%%sql

SELECT *
FROM cats 
WHERE name = 'Egg'

   cat_id name    breed  age
0       4  Egg  Persian    4

In [14]:
%%sql

SELECT *
FROM cats 
WHERE age > 4

   cat_id            name       breed  age
0       2           Cindy  Maine Coon   10
1       3      Dumbledore  Maine Coon   11
2       5           Misty       Tabby   13
3       6  George Michael     Ragdoll    9
4       7         Jackson      Sphynx    7

# Update
#### Always do a SELECT query to confirm before UPDATE to make sure your target is accurate 
```sql
UPDATE table_name SET column_name = 'updated_value'
WHERE condition
```

In [32]:
%%sql

USE dog_world;

CREATE TABLE employees
    (
        employee_id INT AUTO_INCREMENT,
        first_name VARCHAR(50) NOT NULL,
        last_name VARCHAR(50) NOT NULL,
        position VARCHAR(50) NOT NULL,
        PRIMARY KEY(employee_id)
    )

Empty DataFrame
Columns: []
Index: []

In [33]:
%%sql

INSERT INTO employees (first_name, last_name, position)
VALUES
    ('Adam', 'Shaw', ' Lead Engineer'),
    ('Darin', 'John', ' Junior Engineer'),
    ('Stephen', 'Kyler', ' BI Engineer'),
    ('Kayla', 'Johnson', ' Lead BI Engineer'),
    ('Brad', 'Tyler', ' Senior Software Engineer');

Empty DataFrame
Columns: []
Index: []

In [34]:
%%sql

SELECT *
FROM employees

   employee_id first_name last_name                   position
0            1       Adam      Shaw              Lead Engineer
1            2      Darin      John            Junior Engineer
2            3    Stephen     Kyler                BI Engineer
3            4      Kayla   Johnson           Lead BI Engineer
4            5       Brad     Tyler   Senior Software Engineer

#### UPDATE

In [36]:
%%sql

UPDATE employees SET last_name = 'Johnson'
WHERE 
    first_name = 'Darin';

Empty DataFrame
Columns: []
Index: []

In [37]:
%%sql

SELECT *
FROM employees

   employee_id first_name last_name                   position
0            1       Adam      Shaw              Lead Engineer
1            2      Darin   Johnson            Junior Engineer
2            3    Stephen     Kyler                BI Engineer
3            4      Kayla   Johnson           Lead BI Engineer
4            5       Brad     Tyler   Senior Software Engineer

#### Multi - UPDATE

In [38]:
%%sql

UPDATE employees SET last_name = 'bad_johnson', position = 'termianted'
WHERE first_name = 'Darin'

Empty DataFrame
Columns: []
Index: []

In [39]:
%%sql

SELECT *
FROM employees

   employee_id first_name    last_name                   position
0            1       Adam         Shaw              Lead Engineer
1            2      Darin  bad_johnson                 termianted
2            3    Stephen        Kyler                BI Engineer
3            4      Kayla      Johnson           Lead BI Engineer
4            5       Brad        Tyler   Senior Software Engineer