#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# WITH ROLLUP
#### WITH ROLLUP is a modifier added to the GROUP BY clause that automatically calculates hierarchical subtotals and a grand total within a single query result.

In [4]:
%%sql

USE tv_shows;

SELECT 
    AVG(rating)
FROM full_review

  AVG(rating)
0     8.02553

In [7]:
%%sql

SELECT 
    title,
    AVG(rating) AS avg_rating
FROM full_review
GROUP BY title

                   title avg_rating
0                 Archer    8.12000
1   Arrested Development    8.08000
2          Bob's Burgers    7.52000
3        Bojack Horseman    7.94000
4           Breaking Bad    9.36000
5   Curb Your Enthusiasm    8.12000
6                  Fargo    9.40000
7       Freaks and Geeks    8.60000
8       General Hospital    5.38000
9    Halt and Catch Fire    9.90000
10              Seinfeld    7.60000
11       Stranger Things    8.76667

# WITH ROLLUP
#### This will add a NULL/NONE row at the end which will have the summary of the entire table

In [8]:
%%sql

SELECT 
    title,
    AVG(rating) AS avg_rating
FROM full_review
GROUP BY title
WITH ROLLUP

                   title avg_rating
0                 Archer    8.12000
1   Arrested Development    8.08000
2          Bob's Burgers    7.52000
3        Bojack Horseman    7.94000
4           Breaking Bad    9.36000
5   Curb Your Enthusiasm    8.12000
6                  Fargo    9.40000
7       Freaks and Geeks    8.60000
8       General Hospital    5.38000
9    Halt and Catch Fire    9.90000
10              Seinfeld    7.60000
11       Stranger Things    8.76667
12                  None    8.02553

In [10]:
%%sql

SELECT 
    title,
    COUNT(rating) AS count_rating
FROM full_review
GROUP BY title
WITH ROLLUP

                   title  count_rating
0                 Archer             5
1   Arrested Development             5
2          Bob's Burgers             5
3        Bojack Horseman             5
4           Breaking Bad             5
5   Curb Your Enthusiasm             5
6                  Fargo             2
7       Freaks and Geeks             4
8       General Hospital             5
9    Halt and Catch Fire             1
10              Seinfeld             2
11       Stranger Things             3
12                  None            47

In [14]:
%%sql

SELECT 
    title,
    genre,
    COUNT(rating) AS count_rating
FROM full_review
GROUP BY title, genre
WITH ROLLUP

                   title      genre  count_rating
0                 Archer  Animation             5
1                 Archer       None             5
2   Arrested Development     Comedy             5
3   Arrested Development       None             5
4          Bob's Burgers  Animation             5
5          Bob's Burgers       None             5
6        Bojack Horseman  Animation             5
7        Bojack Horseman       None             5
8           Breaking Bad      Drama             5
9           Breaking Bad       None             5
10  Curb Your Enthusiasm     Comedy             5
11  Curb Your Enthusiasm       None             5
12                 Fargo      Drama             2
13                 Fargo       None             2
14      Freaks and Geeks     Comedy             4
15      Freaks and Geeks       None             4
16      General Hospital      Drama             5
17      General Hospital       None             5
18   Halt and Catch Fire      Drama             1
19   Halt and Catch Fire       None             1
20              Seinfeld     Comedy             2
21              Seinfeld       None             2
22       Stranger Things      Drama             3
23       Stranger Things       None             3
24                  None       None            47