#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Aggregate Functions Exercise

In [3]:
%%sql

USE book_shop;

SELECT *
FROM books
LIMIT 2;

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304

#### Print the number of books in the database

In [6]:
%%sql

SELECT
    COUNT(*) AS total_books
FROM books

   total_books
0           19

#### Print out how many books were released in each year

In [7]:
%%sql

SELECT
    released_year,
    COUNT(*) AS '# of books'
FROM books
GROUP BY released_year

    released_year  # of books
0            2003           2
1            2016           1
2            2001           3
3            1996           1
4            2012           1
5            2013           1
6            2000           1
7            2010           1
8            1981           1
9            1989           1
10           1985           1
11           1945           1
12           2004           1
13           2005           1
14           2014           1
15           2017           1

#### Print out the total number of books in stock

In [8]:
%%sql

SELECT 
    SUM(stock_quantity)
FROM books

  SUM(stock_quantity)
0                2450

#### Find the average released_year for each author

In [10]:
%%sql

SELECT 
    CONCAT(author_fname, ' ', author_lname) AS author_name,
    ROUND(AVG(released_year), 0)
FROM books
GROUP BY author_name

             author_name ROUND(AVG(released_year), 0)
0          Jhumpa Lahiri                         2000
1            Neil Gaiman                         2007
2            Dave Eggers                         2009
3         Michael Chabon                         2000
4            Patti Smith                         2010
5         Raymond Carver                         1985
6            Don DeLillo                         1985
7         John Steinbeck                         1945
8   David Foster Wallace                         2005
9             Dan Harris                         2014
10         Freida Harris                         2001
11       George Saunders                         2017

#### Find the full name of the author who wrote the longest book

In [13]:
%%sql

SELECT
    CONCAT(author_fname, ' ', author_lname) AS author_name,
    pages
FROM books
WHERE pages = (
    SELECT 
        MAX(pages)
    FROM books
)

      author_name  pages
0  Michael Chabon    634

In [14]:
%%sql

SELECT
    released_year,
    COUNT(*) AS '# books',
    AVG(pages)
FROM books
GROUP BY released_year
ORDER BY released_year

    released_year  # books AVG(pages)
0            1945        1   181.0000
1            1981        1   176.0000
2            1985        1   320.0000
3            1989        1   526.0000
4            1996        1   198.0000
5            2000        1   634.0000
6            2001        3   443.3333
7            2003        2   249.5000
8            2004        1   329.0000
9            2005        1   343.0000
10           2010        1   304.0000
11           2012        1   352.0000
12           2013        1   504.0000
13           2014        1   256.0000
14           2016        1   304.0000
15           2017        1   367.0000