#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# CRUD Challenge
1. Create a new database 'shirts_db'
2. Create a new table called 'shirts'
3. Columns : shirt_id, article, color, shirt_size, last_worn 
4. Primary Key is shirt_id
5. Insert provided data
6. Add a New Shirt : Purple polo shirt, size M, last worn 50 days ago
7. Select all shirts but only print out article and color
8. Select all medium shirts. Print out everything BUT shirt_id
9. Update all polo shirts : Change theur size to L
10. Update the shirt that was last worn 15 days ago -> Change last_worn to 0
11. Update all white shirts -> Change size to 'XS' and color to 'off white'
12. Delete all old shirts -> Last worn 200 days ago
13. Delete all tank tops
14. Delete all shirts
15. Drop the enture shirts table

#### 1. Create a new database 'shirts_db'

In [2]:
%%sql

CREATE DATABASE shirts_db

Empty DataFrame
Columns: []
Index: []

#### 2. Create a new table called 'shirts'
#### 3. Columns : shirt_id, article, color, shirt_size, last_worn 
#### 4. Primary Key is shirt_id

In [3]:
%%sql

USE shirts_db;

CREATE TABLE shirts
    (
        shirt_id INT AUTO_INCREMENT,
        article VARCHAR(50) NOT NULL,
        color VARCHAR(50) NOT NULL,
        shirt_size VARCHAR(10) NOT NULL,
        last_worn INT NOT NULL,
        PRIMARY KEY(shirt_id)
    )

Empty DataFrame
Columns: []
Index: []

#### 5. Insert provided data

In [4]:
%%sql

INSERT INTO shirts (article, color, shirt_size, last_worn)
VALUES
    ('t-shirt', 'white', 'S', 10),
    ('t-shirt', 'green', 'S', 200),
    ('polo shirt', 'black', 'M', 10),
    ('tank top', 'blue', 'S', 50),
    ('t-shirt', 'pink', 'S', 0),
    ('polo shirt', 'red', 'M', 5),
    ('tank top', 'white', 'S', 200),
    ('tank top', 'blue', 'M', 15)

Empty DataFrame
Columns: []
Index: []

#### 6. Add a New Shirt : Purple polo shirt, size M, last worn 50 days ago

In [5]:
%%sql

INSERT INTO shirts (article, color, shirt_size, last_worn)
VALUES ('polo shirt', 'purple', 'M', 50)

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

SELECT *
FROM shirts

   shirt_id     article   color shirt_size  last_worn
0         1     t-shirt   white          S         10
1         2     t-shirt   green          S        200
2         3  polo shirt   black          M         10
3         4    tank top    blue          S         50
4         5     t-shirt    pink          S          0
5         6  polo shirt     red          M          5
6         7    tank top   white          S        200
7         8    tank top    blue          M         15
8         9  polo shirt  purple          M         50

#### 7. Select all shirts but only print out article and color

In [7]:
%%sql

SELECT 
    article,
    color
FROM shirts

      article   color
0     t-shirt   white
1     t-shirt   green
2  polo shirt   black
3    tank top    blue
4     t-shirt    pink
5  polo shirt     red
6    tank top   white
7    tank top    blue
8  polo shirt  purple

#### 8. Select all medium shirts. Print out everything BUT shirt_id

In [8]:
%%sql

SELECT 
    article,
    color,
    shirt_size,
    last_worn
FROM shirts
WHERE shirt_size = 'M'

      article   color shirt_size  last_worn
0  polo shirt   black          M         10
1  polo shirt     red          M          5
2    tank top    blue          M         15
3  polo shirt  purple          M         50

#### 9. Update all polo shirts : Change theur size to L

In [9]:
%%sql

UPDATE shirts SET shirt_size = 'L'
WHERE article = 'polo shirt'

Empty DataFrame
Columns: []
Index: []

In [10]:
%%sql

SELECT *
FROM shirts

   shirt_id     article   color shirt_size  last_worn
0         1     t-shirt   white          S         10
1         2     t-shirt   green          S        200
2         3  polo shirt   black          L         10
3         4    tank top    blue          S         50
4         5     t-shirt    pink          S          0
5         6  polo shirt     red          L          5
6         7    tank top   white          S        200
7         8    tank top    blue          M         15
8         9  polo shirt  purple          L         50

#### 10. Update the shirt that was last worn 15 days ago -> Change last_worn to 0

In [11]:
%%sql

UPDATE shirts SET last_worn = 0
WHERE last_worn = 15

Empty DataFrame
Columns: []
Index: []

In [12]:
%%sql

SELECT *
FROM shirts

   shirt_id     article   color shirt_size  last_worn
0         1     t-shirt   white          S         10
1         2     t-shirt   green          S        200
2         3  polo shirt   black          L         10
3         4    tank top    blue          S         50
4         5     t-shirt    pink          S          0
5         6  polo shirt     red          L          5
6         7    tank top   white          S        200
7         8    tank top    blue          M          0
8         9  polo shirt  purple          L         50

#### 11. Update all white shirts -> Change size to 'XS' and color to 'off white'

In [13]:
%%sql

UPDATE shirts SET shirt_size = 'XS', color = 'off white'
WHERE color = 'white'

Empty DataFrame
Columns: []
Index: []

In [14]:
%%sql

SELECT *
FROM shirts

   shirt_id     article      color shirt_size  last_worn
0         1     t-shirt  off white         XS         10
1         2     t-shirt      green          S        200
2         3  polo shirt      black          L         10
3         4    tank top       blue          S         50
4         5     t-shirt       pink          S          0
5         6  polo shirt        red          L          5
6         7    tank top  off white         XS        200
7         8    tank top       blue          M          0
8         9  polo shirt     purple          L         50

#### 12. Delete all old shirts -> Last worn 200 days ago

In [15]:
%%sql

DELETE FROM shirts
WHERE last_worn = 200

Empty DataFrame
Columns: []
Index: []

In [16]:
%%sql

SELECT *
FROM shirts

   shirt_id     article      color shirt_size  last_worn
0         1     t-shirt  off white         XS         10
1         3  polo shirt      black          L         10
2         4    tank top       blue          S         50
3         5     t-shirt       pink          S          0
4         6  polo shirt        red          L          5
5         8    tank top       blue          M          0
6         9  polo shirt     purple          L         50

#### 13. Delete all tank tops

In [17]:
%%sql

DELETE FROM shirts
WHERE article = 'tank top'

Empty DataFrame
Columns: []
Index: []

In [19]:
%%sql

SELECT *
FROM shirts

   shirt_id     article      color shirt_size  last_worn
0         1     t-shirt  off white         XS         10
1         3  polo shirt      black          L         10
2         5     t-shirt       pink          S          0
3         6  polo shirt        red          L          5
4         9  polo shirt     purple          L         50

#### 14. Delete all shirts

In [20]:
%%sql

DELETE FROM shirts

Empty DataFrame
Columns: []
Index: []

#### 15. Drop the enture shirts table

In [21]:
%%sql

DROP TABLE shirts

Empty DataFrame
Columns: []
Index: []