#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Data Types Exercise

#### Print out the Current Time

In [3]:
%%sql

SELECT 
    CURTIME()

        CURTIME()
0 0 days 13:49:36

#### Print out the current date but not the time

In [4]:
%%sql

SELECT
    CURDATE()

    CURDATE()
0  2026-08-06

#### Print out the Current Day of the Week

In [7]:
%%sql

SELECT
    DAYOFWEEK(CURDATE())

   DAYOFWEEK(CURDATE())
0                     5

In [14]:
%%sql
SELECT 
    DATE_FORMAT(NOW(), '%a')

  DATE_FORMAT(NOW(), '%a')
0                      Thu

#### Create a Tweets table that stores
#### 1. The tweet content 2. A username 3. Time it was created

In [15]:
%%sql

USE dog_world;

CREATE TABLE tweets
    (
        text_content VARCHAR(100),
        username VARCHAR(20), 
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

Empty DataFrame
Columns: []
Index: []

In [18]:
%%sql

INSERT INTO tweets (text_content, username)
VALUES
    ('Hey ! Everyone, I am new here!', 'genguy@gmail.com'),
    ('Yo! Just Chillin!', 'menguy@gmail.com'),
    ('I am the owner of this space!', 'heng@gmail.com')

Empty DataFrame
Columns: []
Index: []

In [20]:
%%sql

SELECT *
FROM tweets

                     text_content          username          created_at
0  Hey ! Everyone, I am new here!  genguy@gmail.com 2026-08-06 14:44:16
1               Yo! Just Chillin!  menguy@gmail.com 2026-08-06 14:44:16
2   I am the owner of this space!    heng@gmail.com 2026-08-06 14:44:16