#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# DELETE Exercise

### DELETE all 4 year old cats

In [3]:
%%sql

USE dog_world;

SELECT *
FROM cats

   cat_id            name              breed  age
0       1           Ringo  British Shorthair    4
1       2           Cindy         Maine Coon   12
2       3      Dumbledore         Maine Coon   12
3       4             Egg            Persian    4
4       5           Misty              Tabby   13
5       6  George Michael            Ragdoll    9
6       7            Jack             Sphynx    7

In [5]:
%%sql

DELETE FROM cats 
WHERE age = 4

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

SELECT *
FROM cats

   cat_id            name       breed  age
0       2           Cindy  Maine Coon   12
1       3      Dumbledore  Maine Coon   12
2       5           Misty       Tabby   13
3       6  George Michael     Ragdoll    9
4       7            Jack      Sphynx    7

### DELETE the cats whose age is the same as their cat_id

In [7]:
%%sql

DELETE FROM cats
WHERE cat_id = age

Empty DataFrame
Columns: []
Index: []

In [8]:
%%sql

SELECT *
FROM cats

   cat_id            name       breed  age
0       2           Cindy  Maine Coon   12
1       3      Dumbledore  Maine Coon   12
2       5           Misty       Tabby   13
3       6  George Michael     Ragdoll    9

### DELETE all cats from the table without dropping the table

In [9]:
%%sql

DELETE FROM cats

Empty DataFrame
Columns: []
Index: []

In [10]:
%%sql

SELECT *
FROM cats

Empty DataFrame
Columns: [cat_id, name, breed, age]
Index: []