#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# JOINS Exercise

In [3]:
%%sql

USE dog_world;

CREATE TABLE students
    (
        id INT AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(50)
    )

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql

CREATE TABLE papers
    (
        title VARCHAR(50),
        grade INT,
        student_id INT,
        FOREIGN KEY (student_id) REFERENCES students(id)
    )

Empty DataFrame
Columns: []
Index: []

In [5]:
%%sql

INSERT INTO students (first_name) VALUES 
('Caleb'), ('Samantha'), ('Raj'), ('Carlos'), ('Lisa');
 
INSERT INTO papers (student_id, title, grade ) VALUES
(1, 'My First Book Report', 60),
(1, 'My Second Book Report', 75),
(2, 'Russian Lit Through The Ages', 94),
(2, 'De Montaigne and The Art of The Essay', 98),
(4, 'Borges and Magical Realism', 89);

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

SELECT *
FROM students

   id first_name
0   1      Caleb
1   2   Samantha
2   3        Raj
3   4     Carlos
4   5       Lisa

In [7]:
%%sql

SELECT *
FROM papers

                                   title  grade  student_id
0                   My First Book Report     60           1
1                  My Second Book Report     75           1
2           Russian Lit Through The Ages     94           2
3  De Montaigne and The Art of The Essay     98           2
4             Borges and Magical Realism     89           4

In [9]:
%%sql

SELECT 
    s.first_name, 
    p.title,
    p.grade
FROM students as s 
JOIN papers as p 
ON s.id = p.student_id
ORDER BY grade DESC

  first_name                                  title  grade
0   Samantha  De Montaigne and The Art of The Essay     98
1   Samantha           Russian Lit Through The Ages     94
2     Carlos             Borges and Magical Realism     89
3      Caleb                  My Second Book Report     75
4      Caleb                   My First Book Report     60

In [11]:
%%sql

SELECT 
    s.first_name, 
    p.title,
    p.grade
FROM students as s 
LEFT JOIN papers as p 
ON s.id = p.student_id

  first_name                                  title  grade
0      Caleb                   My First Book Report   60.0
1      Caleb                  My Second Book Report   75.0
2   Samantha           Russian Lit Through The Ages   94.0
3   Samantha  De Montaigne and The Art of The Essay   98.0
4        Raj                                   None    NaN
5     Carlos             Borges and Magical Realism   89.0
6       Lisa                                   None    NaN

In [13]:
%%sql

SELECT 
    s.first_name, 
    IFNULL(p.title, 'MISSING'),
    IFNULL(p.grade, 0)
FROM students as s 
LEFT JOIN papers as p 
ON s.id = p.student_id

  first_name             IFNULL(p.title, 'MISSING')  IFNULL(p.grade, 0)
0      Caleb                   My First Book Report                  60
1      Caleb                  My Second Book Report                  75
2   Samantha           Russian Lit Through The Ages                  94
3   Samantha  De Montaigne and The Art of The Essay                  98
4        Raj                                MISSING                   0
5     Carlos             Borges and Magical Realism                  89
6       Lisa                                MISSING                   0

In [17]:
%%sql

SELECT
    s.first_name,
    IFNULL(AVG(grade), 0) as average
FROM students as s 
LEFT JOIN papers as p 
ON s.id = p.student_id
GROUP BY s.first_name
ORDER BY average DESC

  first_name  average
0   Samantha  96.0000
1     Carlos  89.0000
2      Caleb  67.5000
3        Raj   0.0000
4       Lisa   0.0000

In [21]:
%%sql

SELECT
    s.first_name,
    IFNULL(AVG(grade), 0) as average,
    CASE 
        WHEN IFNULL(AVG(grade), 0) > 75 THEN 'PASSING'
        ELSE 'FAILING'
    END as passing_status
FROM students as s 
LEFT JOIN papers as p 
ON s.id = p.student_id
GROUP BY s.first_name
ORDER BY average DESC

  first_name  average passing_status
0   Samantha  96.0000        PASSING
1     Carlos  89.0000        PASSING
2      Caleb  67.5000        FAILING
3        Raj   0.0000        FAILING
4       Lisa   0.0000        FAILING