#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Refining Selections Exercise

In [4]:
%%sql

USE book_shop;

SELECT 
    title
FROM books
WHERE title LIKE '%stories%';

                                               title
0  What We Talk About When We Talk About Love: St...
1           Where I'm Calling From: Selected Stories
2                                  Oblivion: Stories

In [6]:
%%sql

SELECT 
    title,
    pages
FROM books
ORDER BY pages DESC
LIMIT 1;

                                       title  pages
0  The Amazing Adventures of Kavalier & Clay    634

In [11]:
%%sql

SELECT 
    CONCAT(title, ' - ', released_year) AS summary
FROM books
ORDER BY released_year DESC
LIMIT 3;

                       summary
0  Lincoln In The Bardo - 2017
1       Norse Mythology - 2016
2           10% Happier - 2014

In [12]:
%%sql

SELECT
    title,
    author_lname
FROM books
WHERE author_lname LIKE '% %'

                  title    author_lname
0     Oblivion: Stories  Foster Wallace
1  Consider the Lobster  Foster Wallace

In [16]:
%%sql

SELECT 
    title,
    released_year,
    stock_quantity
FROM books
ORDER BY stock_quantity 
LIMIT 3;

,title,released_year,stock_quantity
0,Where I'm Calling From: Selected Stories,1989,12
1,American Gods,2001,12
2,What We Talk About When We Talk About Love: St...,1981,23

In [17]:
%%sql

SELECT
    title,
    author_lname
FROM books
ORDER BY author_lname, title

                                                title    author_lname
0   What We Talk About When We Talk About Love: St...          Carver
1            Where I'm Calling From: Selected Stories          Carver
2           The Amazing Adventures of Kavalier & Clay          Chabon
3                                         White Noise         DeLillo
4           A Heartbreaking Work of Staggering Genius          Eggers
5                    A Hologram for the King: A Novel          Eggers
6                                          The Circle          Eggers
7                                Consider the Lobster  Foster Wallace
8                                   Oblivion: Stories  Foster Wallace
9                                       American Gods          Gaiman
10                                           Coraline          Gaiman
11                                    Norse Mythology          Gaiman
12                                        10% Happier          Harris
13                                          fake_book          Harris
14                            Interpreter of Maladies          Lahiri
15                                       The Namesake          Lahiri
16                               Lincoln In The Bardo        Saunders
17                                          Just Kids           Smith
18                                        Cannery Row       Steinbeck

In [24]:
%%sql

SELECT
    UPPER(CONCAT('My Favorite author is ', author_fname, ' ', author_lname, ' !')) AS yell
FROM books
ORDER BY author_lname

                                            yell
0         MY FAVORITE AUTHOR IS RAYMOND CARVER !
1         MY FAVORITE AUTHOR IS RAYMOND CARVER !
2         MY FAVORITE AUTHOR IS MICHAEL CHABON !
3            MY FAVORITE AUTHOR IS DON DELILLO !
4            MY FAVORITE AUTHOR IS DAVE EGGERS !
5            MY FAVORITE AUTHOR IS DAVE EGGERS !
6            MY FAVORITE AUTHOR IS DAVE EGGERS !
7   MY FAVORITE AUTHOR IS DAVID FOSTER WALLACE !
8   MY FAVORITE AUTHOR IS DAVID FOSTER WALLACE !
9            MY FAVORITE AUTHOR IS NEIL GAIMAN !
10           MY FAVORITE AUTHOR IS NEIL GAIMAN !
11           MY FAVORITE AUTHOR IS NEIL GAIMAN !
12            MY FAVORITE AUTHOR IS DAN HARRIS !
13         MY FAVORITE AUTHOR IS FREIDA HARRIS !
14         MY FAVORITE AUTHOR IS JHUMPA LAHIRI !
15         MY FAVORITE AUTHOR IS JHUMPA LAHIRI !
16       MY FAVORITE AUTHOR IS GEORGE SAUNDERS !
17           MY FAVORITE AUTHOR IS PATTI SMITH !
18        MY FAVORITE AUTHOR IS JOHN STEINBECK !