#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Exercise on String Functions

### 1. Reverse and Upper case the following sentence

##### 'Why does my dog keep on eating icecream?'

In [2]:
%%sql

SELECT 
    UPPER(REVERSE('Why does my dog keep on eating icecream?'))

  UPPER(REVERSE('Why does my dog keep on eating icecream?'))
0           ?MAERCECI GNITAE NO PEEK GOD YM SEOD YHW

In [3]:
%%sql

SELECT
  REPLACE
  (
  CONCAT('I', ' ', 'like', ' ', 'cats'),
  ' ',
  '_'
  );

  REPLACE\n  (\n  CONCAT('I', ' ', 'like', ' ', 'cats'),\n  ' ',\n  '_'\n  )
0                                        I_like_cats

In [4]:
%%sql

USE book_shop;

SELECT 
    REPLACE(title, ' ', '->')
FROM books

                            REPLACE(title, ' ', '->')
0                                       The->Namesake
1                                    Norse->Mythology
2                                      American->Gods
3                           Interpreter->of->Maladies
4              A->Hologram->for->the->King:->A->Novel
5                                         The->Circle
6     The->Amazing->Adventures->of->Kavalier->&->Clay
7                                          Just->Kids
8      A->Heartbreaking->Work->of->Staggering->Genius
9                                            Coraline
10  What->We->Talk->About->When->We->Talk->About->...
11      Where->I'm->Calling->From:->Selected->Stories
12                                       White->Noise
13                                       Cannery->Row
14                                 Oblivion:->Stories
15                             Consider->the->Lobster

In [5]:
%%sql

SELECT 
    author_fname AS forwards,
    REVERSE(author_lname) AS backwards
FROM books

   forwards       backwards
0    Jhumpa          irihaL
1      Neil          namiaG
2      Neil          namiaG
3    Jhumpa          irihaL
4      Dave          sreggE
5      Dave          sreggE
6   Michael          nobahC
7     Patti           htimS
8      Dave          sreggE
9      Neil          namiaG
10  Raymond          revraC
11  Raymond          revraC
12      Don         olliLeD
13     John       kcebnietS
14    David  ecallaW retsoF
15    David  ecallaW retsoF

In [7]:
%%sql

SELECT 
    UPPER(
        CONCAT(
            author_fname,
            ' ',
            author_lname
            )) 
            AS 'full name in caps'
FROM books

       full name in caps
0          JHUMPA LAHIRI
1            NEIL GAIMAN
2            NEIL GAIMAN
3          JHUMPA LAHIRI
4            DAVE EGGERS
5            DAVE EGGERS
6         MICHAEL CHABON
7            PATTI SMITH
8            DAVE EGGERS
9            NEIL GAIMAN
10        RAYMOND CARVER
11        RAYMOND CARVER
12           DON DELILLO
13        JOHN STEINBECK
14  DAVID FOSTER WALLACE
15  DAVID FOSTER WALLACE

In [11]:
%%sql

SELECT 
    CONCAT(title, ' was released in ', released_year) AS blurb
FROM books

                                                blurb
0                   The Namesake was released in 2003
1                Norse Mythology was released in 2016
2                  American Gods was released in 2001
3        Interpreter of Maladies was released in 1996
4   A Hologram for the King: A Novel was released ...
5                     The Circle was released in 2013
6   The Amazing Adventures of Kavalier & Clay was ...
7                      Just Kids was released in 2010
8   A Heartbreaking Work of Staggering Genius was ...
9                       Coraline was released in 2003
10  What We Talk About When We Talk About Love: St...
11  Where I'm Calling From: Selected Stories was r...
12                   White Noise was released in 1985
13                   Cannery Row was released in 1945
14             Oblivion: Stories was released in 2004
15          Consider the Lobster was released in 2005

In [14]:
%%sql

SELECT
    title, 
    CHAR_LENGTH(title) AS 'character count'
FROM books
LIMIT 5;

                              title  character count
0                      The Namesake               12
1                   Norse Mythology               15
2                     American Gods               13
3           Interpreter of Maladies               23
4  A Hologram for the King: A Novel               32

In [28]:
%%sql

SELECT 
    CONCAT(SUBSTRING(title, 1, 10), '...') AS 'short title', 
    CONCAT(author_lname, ' ', author_fname) AS author,
    CONCAT(stock_quantity, ' ', 'in stock') AS quantity
FROM books

      short title                author      quantity
0   The Namesa...         Lahiri Jhumpa   32 in stock
1   Norse Myth...           Gaiman Neil   43 in stock
2   American G...           Gaiman Neil   12 in stock
3   Interprete...         Lahiri Jhumpa   97 in stock
4   A Hologram...           Eggers Dave  154 in stock
5   The Circle...           Eggers Dave   26 in stock
6   The Amazin...        Chabon Michael   68 in stock
7    Just Kids...           Smith Patti   55 in stock
8   A Heartbre...           Eggers Dave  104 in stock
9     Coraline...           Gaiman Neil  100 in stock
10  What We Ta...        Carver Raymond   23 in stock
11  Where I'm ...        Carver Raymond   12 in stock
12  White Nois...           DeLillo Don   49 in stock
13  Cannery Ro...        Steinbeck John   95 in stock
14  Oblivion: ...  Foster Wallace David  172 in stock
15  Consider t...  Foster Wallace David   92 in stock

In [23]:
%%sql

SELECT *
FROM books

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304
2,3,American Gods,Neil,Gaiman,2001,12,465
3,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
4,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
5,6,The Circle,Dave,Eggers,2013,26,504
6,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
7,8,Just Kids,Patti,Smith,2010,55,304
8,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
9,10,Coraline,Neil,Gaiman,2003,100,208
10,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
11,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526
12,13,White Noise,Don,DeLillo,1985,49,320
13,14,Cannery Row,John,Steinbeck,1945,95,181
14,15,Oblivion: Stories,David,Foster Wallace,2004,172,329
15,16,Consider the Lobster,David,Foster Wallace,2005,92,343