#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# UPDATE exercise

In [2]:
%%sql

USE dog_world;

SELECT *
FROM cats

   cat_id            name       breed  age
0       1           Ringo       Tabby    4
1       2           Cindy  Maine Coon   10
2       3      Dumbledore  Maine Coon   11
3       4             Egg     Persian    4
4       5           Misty       Tabby   13
5       6  George Michael     Ragdoll    9
6       7         Jackson      Sphynx    7

### UPDATE Jackson's name to Jack

In [3]:
%%sql

UPDATE cats SET name = 'Jack'
WHERE name = 'Jackson'

Empty DataFrame
Columns: []
Index: []

In [4]:
%%sql

SELECT *
FROM cats

   cat_id            name       breed  age
0       1           Ringo       Tabby    4
1       2           Cindy  Maine Coon   10
2       3      Dumbledore  Maine Coon   11
3       4             Egg     Persian    4
4       5           Misty       Tabby   13
5       6  George Michael     Ragdoll    9
6       7            Jack      Sphynx    7

### Change Ringo's breed to 'British Shorthair'

In [5]:
%%sql

UPDATE cats SET breed = 'British Shorthair'
WHERE name = 'Ringo'

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

SELECT *
FROM cats

   cat_id            name              breed  age
0       1           Ringo  British Shorthair    4
1       2           Cindy         Maine Coon   10
2       3      Dumbledore         Maine Coon   11
3       4             Egg            Persian    4
4       5           Misty              Tabby   13
5       6  George Michael            Ragdoll    9
6       7            Jack             Sphynx    7

#### UPDATE both Maine Coons' ages to be 12

In [7]:
%%sql

UPDATE cats SET age = 12
WHERE breed = 'Maine Coon'

Empty DataFrame
Columns: []
Index: []

In [8]:
%%sql

SELECT *
FROM cats

   cat_id            name              breed  age
0       1           Ringo  British Shorthair    4
1       2           Cindy         Maine Coon   12
2       3      Dumbledore         Maine Coon   12
3       4             Egg            Persian    4
4       5           Misty              Tabby   13
5       6  George Michael            Ragdoll    9
6       7            Jack             Sphynx    7