#### Connection to MySQL

In [2]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Date Functions

#### DAY() - Extract the Day of the month from DATES

In [3]:
%%sql

USE dog_world;

SELECT 
    name,
    birth_date,
    DAY(birth_date)
FROM people

    name  birth_date  DAY(birth_date)
0   Matt  2001-12-25               25
1   Lulu  2003-01-20               20
2    Ben  2010-10-02                2
3    Tom  2009-10-22               22
4  Peter  2001-11-28               28
5   Colt  2026-08-06                6

#### DAYOFWEEK() - Using this we can extract the Day of the week from the DATE

In [5]:
%%sql

USE dog_world;

SELECT 
    name,
    birth_date,
    DAY(birth_date) AS Birth_Date, 
    DAYOFWEEK(birth_date) AS WeekDay
FROM people

    name  birth_date  Birth_Date  WeekDay
0   Matt  2001-12-25          25        3
1   Lulu  2003-01-20          20        2
2    Ben  2010-10-02           2        7
3    Tom  2009-10-22          22        5
4  Peter  2001-11-28          28        4
5   Colt  2026-08-06           6        5

#### DAYOFYEAR() - Using this we can extract the day of YEAR

In [6]:
%%sql

USE dog_world;

SELECT 
    name,
    birth_date,
    DAY(birth_date) AS Birth_Date, 
    DAYOFWEEK(birth_date) AS WeekDay,
    DAYOFYEAR(birth_date) AS Dayofyear
FROM people

    name  birth_date  Birth_Date  WeekDay  Dayofyear
0   Matt  2001-12-25          25        3        359
1   Lulu  2003-01-20          20        2         20
2    Ben  2010-10-02           2        7        275
3    Tom  2009-10-22          22        5        295
4  Peter  2001-11-28          28        4        332
5   Colt  2026-08-06           6        5        218

#### MONTHNAME()

In [7]:
%%sql

USE dog_world;

SELECT 
    name,
    birth_date,
    DAY(birth_date) AS Birth_Date, 
    DAYOFWEEK(birth_date) AS WeekDay,
    DAYOFYEAR(birth_date) AS Dayofyear,
    MONTHNAME(birth_date) AS MonthName
FROM people

    name  birth_date  Birth_Date  WeekDay  Dayofyear MonthName
0   Matt  2001-12-25          25        3        359  December
1   Lulu  2003-01-20          20        2         20   January
2    Ben  2010-10-02           2        7        275   October
3    Tom  2009-10-22          22        5        295   October
4  Peter  2001-11-28          28        4        332  November
5   Colt  2026-08-06           6        5        218    August

#### YEAR()

In [9]:
%%sql

USE dog_world;

SELECT 
    name,
    birth_date,
    DAY(birth_date) AS Birth_Date, 
    DAYOFWEEK(birth_date) AS WeekDay,
    DAYOFYEAR(birth_date) AS Dayofyear,
    MONTHNAME(birth_date) AS MonthName,
    YEAR(birth_date)
FROM people

,name,birth_date,Birth_Date,WeekDay,Dayofyear,MonthName,YEAR(birth_date)
0,Matt,2001-12-25,25,3,359,December,2001
1,Lulu,2003-01-20,20,2,20,January,2003
2,Ben,2010-10-02,2,7,275,October,2010
3,Tom,2009-10-22,22,5,295,October,2009
4,Peter,2001-11-28,28,4,332,November,2001
5,Colt,2026-08-06,6,5,218,August,2026