#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# TIME Functions

#### HOUR()

In [2]:
%%sql

USE dog_world;

SELECT
    name, 
    birth_date, 
    birth_time,
    HOUR(birth_time)
FROM people

    name  birth_date      birth_time  HOUR(birth_time)
0   Matt  2001-12-25 0 days 11:00:00                11
1   Lulu  2003-01-20 0 days 23:59:10                23
2    Ben  2010-10-02 0 days 11:15:10                11
3    Tom  2009-10-22 0 days 13:01:30                13
4  Peter  2001-11-28 0 days 11:30:20                11
5   Colt  2026-08-06 0 days 09:51:57                 9

#### MINUTE()

In [3]:
%%sql

USE dog_world;

SELECT
    name, 
    birth_date, 
    birth_time,
    HOUR(birth_time),
    MINUTE(birth_time)
FROM people

    name  birth_date      birth_time  HOUR(birth_time)  MINUTE(birth_time)
0   Matt  2001-12-25 0 days 11:00:00                11                   0
1   Lulu  2003-01-20 0 days 23:59:10                23                  59
2    Ben  2010-10-02 0 days 11:15:10                11                  15
3    Tom  2009-10-22 0 days 13:01:30                13                   1
4  Peter  2001-11-28 0 days 11:30:20                11                  30
5   Colt  2026-08-06 0 days 09:51:57                 9                  51

#### SECOND()

In [4]:
%%sql

USE dog_world;

SELECT
    name, 
    birth_date, 
    birth_time,
    HOUR(birth_time),
    MINUTE(birth_time),
    SECOND(birth_time)
FROM people

,name,birth_date,birth_time,HOUR(birth_time),MINUTE(birth_time),SECOND(birth_time)
0,Matt,2001-12-25,0 days 11:00:00,11,0,0
1,Lulu,2003-01-20,0 days 23:59:10,23,59,10
2,Ben,2010-10-02,0 days 11:15:10,11,15,10
3,Tom,2009-10-22,0 days 13:01:30,13,1,30
4,Peter,2001-11-28,0 days 11:30:20,11,30,20
5,Colt,2026-08-06,0 days 09:51:57,9,51,57