#### MySQL connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# TIMESTAMP()
#### A TIMESTAMP takes smaller space in memory as compared to DATETIME

### DATETIME vs TIMESTAMP

| Description | DATETIME | TIMESTAMP |
|---|---|---|
| Format | YYYY-MM-DD HH:MM:SS | YYYY-MM-DD HH:MM:SS |
| Range | January 1, 1000 to December 31, 9999 | January 1, 1970 to December 31, 2038 |
| Storage Size | 8 bytes | 4 bytes (pre-2038) / 8 bytes (post-2038) |
| Timezone | No timezone conversion | Converts to/from UTC based on server timezone |
| Default Value | No automatic updates | Can auto-update with `DEFAULT CURRENT_TIMESTAMP` and `ON UPDATE CURRENT_TIMESTAMP` |

# When we use NOW() we are using a TIMESTAMP and not DATETIME

In [2]:
%%sql

USE dog_world;

CREATE TABLE captions 
    (
        text VARCHAR(200),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

Empty DataFrame
Columns: []
Index: []

In [3]:
%%sql

INSERT INTO captions (text)
VALUES
    ('This is MySQL learning in peogress')

Empty DataFrame
Columns: []
Index: []

In [5]:
%%sql

INSERT INTO captions (text)
VALUES
    ('Today we discussed Date and Time properties'),
    ('We also learnt about TIMESTAMPS as well')

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

SELECT *
FROM captions

                                          text          created_at
0           This is MySQL learning in peogress 2026-08-06 13:24:11
1  Today we discussed Date and Time properties 2026-08-06 13:25:20
2      We also learnt about TIMESTAMPS as well 2026-08-06 13:25:20

#### Adding a column to the table that can store UPDATED_AT values

In [19]:
%%sql

USE dog_world;

ALTER TABLE captions        
    ADD COLUMN updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

Empty DataFrame
Columns: []
Index: []

In [20]:
%%sql

INSERT INTO captions (text)
VALUES ('How was your day today ?')

Empty DataFrame
Columns: []
Index: []

In [21]:
%%sql

SELECT *
FROM captions

                                          text          created_at updated_at
0           This is MySQL learning in peogress 2026-08-06 13:24:11       None
1  Today we discussed Date and Time properties 2026-08-06 13:25:20       None
2      We also learnt about TIMESTAMPS as well 2026-08-06 13:25:20       None
3                     How was your day today ? 2026-08-06 13:42:23       None

In [22]:
%%sql

UPDATE captions SET text = 'How is Life going ?'
WHERE text = 'How was your day today ?'

Empty DataFrame
Columns: []
Index: []

In [23]:
%%sql

SELECT *
FROM captions

,text,created_at,updated_at
0,This is MySQL learning in peogress,2026-08-06 13:24:11,NaT
1,Today we discussed Date and Time properties,2026-08-06 13:25:20,NaT
2,We also learnt about TIMESTAMPS as well,2026-08-06 13:25:20,NaT
3,How is Life going ?,2026-08-06 13:42:23,2026-08-06 13:42:31