In [10]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

# Creating Tables
```sql
CREATE TABLE table_name 
    (
        column_1 VARCHAR(100),
        column_2 INT
    );
```

#### Let us create a sample database called 'dog_world'

In [11]:
%%sql

CREATE DATABASE dog_world

Empty DataFrame
Columns: []
Index: []

#### Inside dog_world database we will create a table called 'dogs'
#### For the name column we will give a VARCHAR limit of 50

In [12]:
%%sql

USE dog_world;

CREATE TABLE dogs
(
    name VARCHAR(50),
    age INT
);

Empty DataFrame
Columns: []
Index: []

# Show Tables in the current Database

In [13]:
%%sql

USE dog_world;

SHOW TABLES

  Tables_in_dog_world
0                dogs

# Show Columns in a particular Table

In [14]:
%%sql

USE dog_world;

SHOW COLUMNS FROM dogs

  Field         Type Null Key Default Extra
0  name  varchar(50)  YES        None
1   age          int  YES        None

# DESCRIBE / DESC a Table

In [15]:
%%sql

USE dog_world;

DESCRIBE dogs

  Field         Type Null Key Default Extra
0  name  varchar(50)  YES        None
1   age          int  YES        None

# Dropping/Deleting Tables

In [16]:
%%sql

USE dog_world;

DROP TABLE dogs;

Empty DataFrame
Columns: []
Index: []

In [17]:
%%sql

SHOW TABLES

Empty DataFrame
Columns: [Tables_in_dog_world]
Index: []

# Tables Basics Activity
#### 1. Create a 'pastries' table which should include 2 columns : name and quantity. 
#### 2. Name is 50 char max
#### 3. Inspect the table
#### 4. Delete the table

In [18]:
%%sql

USE dog_world;

CREATE TABLE pastries
    (
        name VARCHAR(50),
        quantity INT
    )

Empty DataFrame
Columns: []
Index: []

In [20]:
%%sql

USE dog_world;

DESCRIBE pastries

      Field         Type Null Key Default Extra
0      name  varchar(50)  YES        None
1  quantity          int  YES        None

In [21]:
%%sql

USE dog_world;

DROP TABLE pastries

Empty DataFrame
Columns: []
Index: []