#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# SQL VIEWS
#### SQL view is a virtual table generated by the result set of a pre-defined SELECT query. Unlike standard database tables, a standard view does not store physical data; instead, it acts as a dynamic window that queries underlying "base" tables in real time whenever it is called.

In [7]:
%%sql

USE tv_shows;

SHOW TABLES

  Tables_in_tv_shows
0          reviewers
1            reviews
2             series

In [11]:
%%sql

USE tv_shows;

SELECT *
FROM series
LIMIT 5;

   id                 title  released_year      genre
0   1                Archer           2009  Animation
1   2  Arrested Development           2003     Comedy
2   3         Bob's Burgers           2011  Animation
3   4       Bojack Horseman           2014  Animation
4   5          Breaking Bad           2008      Drama

In [12]:
%%sql

USE tv_shows;

SELECT *
FROM reviews
LIMIT 5;

   id rating  series_id  reviewer_id
0   1    8.0          1            1
1   2    7.5          1            2
2   3    8.5          1            3
3   4    7.7          1            4
4   5    8.9          1            5

In [13]:
%%sql

USE tv_shows;

SELECT *
FROM reviewers
LIMIT 5;

   id first_name last_name
0   1     Thomas  Stoneman
1   2      Wyatt    Skaggs
2   3     Kimbra   Masters
3   4    Domingo    Cortes
4   5       Colt    Steele

In [17]:
%%sql

CREATE VIEW full_review AS 
SELECT 
    title,
    released_year,
    genre,
    rating,
    first_name,
    last_name
FROM series as s 
JOIN reviews as r
ON s.id = r.series_id
JOIN reviewers as rv 
ON r.reviewer_id = rv.id

Empty DataFrame
Columns: []
Index: []

In [21]:
%%sql

SELECT *
FROM full_review
LIMIT 5;

                  title  released_year      genre rating first_name last_name
0                Archer           2009  Animation    8.0     Thomas  Stoneman
1  Arrested Development           2003     Comedy    8.1     Thomas  Stoneman
2         Bob's Burgers           2011  Animation    7.0     Thomas  Stoneman
3       Bojack Horseman           2014  Animation    7.5     Thomas  Stoneman
4          Breaking Bad           2008      Drama    9.5     Thomas  Stoneman

# REPLACE - altering a VIEW
# CREATE OR REPLACE VIEW
# ALTER VIEW

In [24]:
%%sql

CREATE OR REPLACE VIEW full_review AS 
SELECT 
    title,
    released_year,
    genre,
    rating,
    first_name,
    last_name
FROM series as s 
JOIN reviews as r
ON s.id = r.series_id
JOIN reviewers as rv 
ON r.reviewer_id = rv.id
ORDER BY title DESC

Empty DataFrame
Columns: []
Index: []

In [25]:
%%sql

ALTER VIEW full_review AS 
SELECT 
    title,
    released_year,
    genre,
    rating,
    first_name,
    last_name
FROM series as s 
JOIN reviews as r
ON s.id = r.series_id
JOIN reviewers as rv 
ON r.reviewer_id = rv.id
ORDER BY genre DESC

Empty DataFrame
Columns: []
Index: []