#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# LEAD & LAG
#### LEAD() and LAG() are window functions used to look forward or backward into adjacent rows within a result set without needing a self-join

# LAG()

#### If we apply LAG it will evalaute the previous employee salary

In [3]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    LAG(salary) OVER(ORDER BY salary DESC) AS lag_salary
FROM employees

    emp_no        department  salary  lag_salary
0       10             sales  159000         NaN
1        4       engineering  103000    159000.0
2        7       engineering   91000    103000.0
3        6       engineering   89000     91000.0
4        1       engineering   80000     89000.0
5       11             sales   72000     80000.0
6        3       engineering   70000     72000.0
7        9             sales   70000     70000.0
8        2       engineering   69000     70000.0
9        5       engineering   67000     69000.0
10      13             sales   61000     67000.0
11      14             sales   61000     61000.0
12      17  customer service   61000     61000.0
13      12             sales   60000     61000.0
14       8             sales   59000     60000.0
15      20  customer service   56000     59000.0
16      21  customer service   55000     56000.0
17      16  customer service   45000     55000.0
18      18  customer service   40000     45000.0
19      15  customer service   38000     40000.0
20      19  customer service   31000     38000.0

### Calcualte the salary diff

In [5]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    salary - LAG(salary) OVER(ORDER BY salary DESC) AS salary_diff
FROM employees

    emp_no        department  salary  salary_diff
0       10             sales  159000          NaN
1        4       engineering  103000     -56000.0
2        7       engineering   91000     -12000.0
3        6       engineering   89000      -2000.0
4        1       engineering   80000      -9000.0
5       11             sales   72000      -8000.0
6        3       engineering   70000      -2000.0
7        9             sales   70000          0.0
8        2       engineering   69000      -1000.0
9        5       engineering   67000      -2000.0
10      13             sales   61000      -6000.0
11      14             sales   61000          0.0
12      17  customer service   61000          0.0
13      12             sales   60000      -1000.0
14       8             sales   59000      -1000.0
15      20  customer service   56000      -3000.0
16      21  customer service   55000      -1000.0
17      16  customer service   45000     -10000.0
18      18  customer service   40000      -5000.0
19      15  customer service   38000      -2000.0
20      19  customer service   31000      -7000.0

In [12]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    salary - LAG(salary) OVER(PARTITION BY department ORDER BY salary DESC) AS dept_salary_diff,
    salary - LAG(salary) OVER(ORDER BY salary DESC) AS salary_diff
FROM employees

    emp_no        department  salary  dept_salary_diff  salary_diff
0       10             sales  159000               NaN          NaN
1        4       engineering  103000               NaN     -56000.0
2        7       engineering   91000          -12000.0     -12000.0
3        6       engineering   89000           -2000.0      -2000.0
4        1       engineering   80000           -9000.0      -9000.0
5       11             sales   72000          -87000.0      -8000.0
6        3       engineering   70000          -10000.0      -2000.0
7        9             sales   70000           -2000.0          0.0
8        2       engineering   69000           -1000.0      -1000.0
9        5       engineering   67000           -2000.0      -2000.0
10      17  customer service   61000               NaN      -6000.0
11      13             sales   61000           -9000.0          0.0
12      14             sales   61000               0.0          0.0
13      12             sales   60000           -1000.0      -1000.0
14       8             sales   59000           -1000.0      -1000.0
15      20  customer service   56000           -5000.0      -3000.0
16      21  customer service   55000           -1000.0      -1000.0
17      16  customer service   45000          -10000.0     -10000.0
18      18  customer service   40000           -5000.0      -5000.0
19      15  customer service   38000           -2000.0      -2000.0
20      19  customer service   31000           -7000.0      -7000.0

# LEAD()

In [7]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    LEAD(salary) OVER(ORDER BY salary DESC) AS lead_salary
FROM employees

    emp_no        department  salary  lead_salary
0       10             sales  159000     103000.0
1        4       engineering  103000      91000.0
2        7       engineering   91000      89000.0
3        6       engineering   89000      80000.0
4        1       engineering   80000      72000.0
5       11             sales   72000      70000.0
6        3       engineering   70000      70000.0
7        9             sales   70000      69000.0
8        2       engineering   69000      67000.0
9        5       engineering   67000      61000.0
10      13             sales   61000      61000.0
11      14             sales   61000      61000.0
12      17  customer service   61000      60000.0
13      12             sales   60000      59000.0
14       8             sales   59000      56000.0
15      20  customer service   56000      55000.0
16      21  customer service   55000      45000.0
17      16  customer service   45000      40000.0
18      18  customer service   40000      38000.0
19      15  customer service   38000      31000.0
20      19  customer service   31000          NaN

In [8]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    salary - LEAD(salary) OVER(ORDER BY salary DESC) AS salary_diff
FROM employees

    emp_no        department  salary  salary_diff
0       10             sales  159000      56000.0
1        4       engineering  103000      12000.0
2        7       engineering   91000       2000.0
3        6       engineering   89000       9000.0
4        1       engineering   80000       8000.0
5       11             sales   72000       2000.0
6        3       engineering   70000          0.0
7        9             sales   70000       1000.0
8        2       engineering   69000       2000.0
9        5       engineering   67000       6000.0
10      13             sales   61000          0.0
11      14             sales   61000          0.0
12      17  customer service   61000       1000.0
13      12             sales   60000       1000.0
14       8             sales   59000       3000.0
15      20  customer service   56000       1000.0
16      21  customer service   55000      10000.0
17      16  customer service   45000       5000.0
18      18  customer service   40000       2000.0
19      15  customer service   38000       7000.0
20      19  customer service   31000          NaN