#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# NTILE()
#### The NTILE(N) window function in MySQL divides an ordered result set into N approximately equal-sized groups (buckets) and assigns a bucket number (from 1 to N) to each row. It is commonly used for statistical calculations like quartiles (NTILE(4)), deciles (NTILE(10)), or percentiles (NTILE(100))

In [4]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    NTILE(4) OVER(ORDER BY salary DESC) AS salary_quartile
FROM employees

    emp_no        department  salary  salary_quartile
0       10             sales  159000                1
1        4       engineering  103000                1
2        7       engineering   91000                1
3        6       engineering   89000                1
4        1       engineering   80000                1
5       11             sales   72000                1
6        3       engineering   70000                2
7        9             sales   70000                2
8        2       engineering   69000                2
9        5       engineering   67000                2
10      13             sales   61000                2
11      14             sales   61000                3
12      17  customer service   61000                3
13      12             sales   60000                3
14       8             sales   59000                3
15      20  customer service   56000                3
16      21  customer service   55000                4
17      16  customer service   45000                4
18      18  customer service   40000                4
19      15  customer service   38000                4
20      19  customer service   31000                4

In [7]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    NTILE(4) OVER(PARTITION BY department ORDER BY salary DESC) AS dept_salary_quart,
    NTILE(4) OVER(ORDER BY salary DESC) AS salary_quartile
FROM employees

    emp_no        department  salary  dept_salary_quart  salary_quartile
0       10             sales  159000                  1                1
1        4       engineering  103000                  1                1
2        7       engineering   91000                  1                1
3        6       engineering   89000                  2                1
4        1       engineering   80000                  2                1
5       11             sales   72000                  1                1
6        3       engineering   70000                  3                2
7        9             sales   70000                  2                2
8        2       engineering   69000                  3                2
9        5       engineering   67000                  4                2
10      17  customer service   61000                  1                2
11      13             sales   61000                  2                3
12      14             sales   61000                  3                3
13      12             sales   60000                  3                3
14       8             sales   59000                  4                3
15      20  customer service   56000                  1                3
16      21  customer service   55000                  2                4
17      16  customer service   45000                  2                4
18      18  customer service   40000                  3                4
19      15  customer service   38000                  3                4
20      19  customer service   31000                  4                4