#### MySQL Connection

In [3]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# WINDOW FUNCTIONS
#### Window functions in MySQL perform calculations across a set of table rows related to the current row while retaining individual row details instead of collapsing them into a single summary row like a standard GROUP BY clause.
#### Window functions perform aggregate operations on group of rows, but they produce a result for each row

# OVER()
#### The OVER() clause constructs a window. When it is empty, the window will include all records

In [6]:
%%sql

USE dog_world;

CREATE TABLE employees (
    emp_no INT PRIMARY KEY AUTO_INCREMENT,
    department VARCHAR(20),
    salary INT
);

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

INSERT INTO employees (department, salary) VALUES
('engineering', 80000),
('engineering', 69000),
('engineering', 70000),
('engineering', 103000),
('engineering', 67000),
('engineering', 89000),
('engineering', 91000),
('sales', 59000),
('sales', 70000),
('sales', 159000),
('sales', 72000),
('sales', 60000),
('sales', 61000),
('sales', 61000),
('customer service', 38000),
('customer service', 45000),
('customer service', 61000),
('customer service', 40000),
('customer service', 31000),
('customer service', 56000),
('customer service', 55000);

Empty DataFrame
Columns: []
Index: []

#### Using a normal GROUP BY

In [6]:
%%sql

USE dog_world;

SELECT 
    department,
    AVG(salary)
FROM employees
GROUP BY department

         department AVG(salary)
0       engineering  81285.7143
1             sales  77428.5714
2  customer service  46571.4286

#### Using OVER()

In [11]:
%%sql

SELECT 
    department,
    AVG(salary) OVER()
FROM employees
LIMIT 5;

    department AVG(salary) OVER()
0  engineering         68428.5714
1  engineering         68428.5714
2  engineering         68428.5714
3  engineering         68428.5714
4  engineering         68428.5714

In [7]:
%%sql

SELECT 
    emp_no,
    department,
    AVG(salary) OVER()
FROM employees

    emp_no        department AVG(salary) OVER()
0        1       engineering         68428.5714
1        2       engineering         68428.5714
2        3       engineering         68428.5714
3        4       engineering         68428.5714
4        5       engineering         68428.5714
5        6       engineering         68428.5714
6        7       engineering         68428.5714
7        8             sales         68428.5714
8        9             sales         68428.5714
9       10             sales         68428.5714
10      11             sales         68428.5714
11      12             sales         68428.5714
12      13             sales         68428.5714
13      14             sales         68428.5714
14      15  customer service         68428.5714
15      16  customer service         68428.5714
16      17  customer service         68428.5714
17      18  customer service         68428.5714
18      19  customer service         68428.5714
19      20  customer service         68428.5714
20      21  customer service         68428.5714

In [16]:
%%sql

SELECT 
    emp_no,
    department,
    MIN(salary) OVER(),
    MAX(salary) OVER()
FROM employees
LIMIT 10;

   emp_no   department  MIN(salary) OVER()  MAX(salary) OVER()
0       1  engineering               31000              159000
1       2  engineering               31000              159000
2       3  engineering               31000              159000
3       4  engineering               31000              159000
4       5  engineering               31000              159000
5       6  engineering               31000              159000
6       7  engineering               31000              159000
7       8        sales               31000              159000
8       9        sales               31000              159000
9      10        sales               31000              159000