#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# PARTITION BY
### OVER(PARTITION BY)
#### Inside of the OVER(), use PARTITION BY to form rows into groups of row
#### The PARTITION BY clause divides a result set into smaller groups (partitions) so that calculations can be performed independently within each group.

In [6]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    AVG(salary) OVER(PARTITION BY department) AS department_avg
FROM employees

    emp_no        department  salary department_avg
0       15  customer service   38000     46571.4286
1       16  customer service   45000     46571.4286
2       17  customer service   61000     46571.4286
3       18  customer service   40000     46571.4286
4       19  customer service   31000     46571.4286
5       20  customer service   56000     46571.4286
6       21  customer service   55000     46571.4286
7        1       engineering   80000     81285.7143
8        2       engineering   69000     81285.7143
9        3       engineering   70000     81285.7143
10       4       engineering  103000     81285.7143
11       5       engineering   67000     81285.7143
12       6       engineering   89000     81285.7143
13       7       engineering   91000     81285.7143
14       8             sales   59000     77428.5714
15       9             sales   70000     77428.5714
16      10             sales  159000     77428.5714
17      11             sales   72000     77428.5714
18      12             sales   60000     77428.5714
19      13             sales   61000     77428.5714
20      14             sales   61000     77428.5714

In [7]:
%%sql

SELECT 
    emp_no, 
    department,
    salary,
    COUNT(*) OVER(PARTITION BY department) AS department_count
FROM employees

    emp_no        department  salary  department_count
0       15  customer service   38000                 7
1       16  customer service   45000                 7
2       17  customer service   61000                 7
3       18  customer service   40000                 7
4       19  customer service   31000                 7
5       20  customer service   56000                 7
6       21  customer service   55000                 7
7        1       engineering   80000                 7
8        2       engineering   69000                 7
9        3       engineering   70000                 7
10       4       engineering  103000                 7
11       5       engineering   67000                 7
12       6       engineering   89000                 7
13       7       engineering   91000                 7
14       8             sales   59000                 7
15       9             sales   70000                 7
16      10             sales  159000                 7
17      11             sales   72000                 7
18      12             sales   60000                 7
19      13             sales   61000                 7
20      14             sales   61000                 7

In [9]:
%%sql

SELECT 
    emp_no, 
    department,
    salary,
    SUM(salary) OVER(PARTITION BY department) AS department_payroll,
    SUM(salary) OVER() AS total_payroll
FROM employees

    emp_no        department  salary department_payroll total_payroll
0       15  customer service   38000             326000       1437000
1       16  customer service   45000             326000       1437000
2       17  customer service   61000             326000       1437000
3       18  customer service   40000             326000       1437000
4       19  customer service   31000             326000       1437000
5       20  customer service   56000             326000       1437000
6       21  customer service   55000             326000       1437000
7        1       engineering   80000             569000       1437000
8        2       engineering   69000             569000       1437000
9        3       engineering   70000             569000       1437000
10       4       engineering  103000             569000       1437000
11       5       engineering   67000             569000       1437000
12       6       engineering   89000             569000       1437000
13       7       engineering   91000             569000       1437000
14       8             sales   59000             542000       1437000
15       9             sales   70000             542000       1437000
16      10             sales  159000             542000       1437000
17      11             sales   72000             542000       1437000
18      12             sales   60000             542000       1437000
19      13             sales   61000             542000       1437000
20      14             sales   61000             542000       1437000