#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# RANK()
#### RANK() window function in MySQL assigns a rank to each row within a partition of a result set, producing non-consecutive ranks with gaps when identical values (ties) are found.

#### From the employees data use RANK() to find out the ranking by salary

In [4]:
%%sql

USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    RANK() OVER(ORDER BY salary DESC) AS overall_salary_rank
FROM employees

    emp_no        department  salary  overall_salary_rank
0       10             sales  159000                    1
1        4       engineering  103000                    2
2        7       engineering   91000                    3
3        6       engineering   89000                    4
4        1       engineering   80000                    5
5       11             sales   72000                    6
6        3       engineering   70000                    7
7        9             sales   70000                    7
8        2       engineering   69000                    9
9        5       engineering   67000                   10
10      13             sales   61000                   11
11      14             sales   61000                   11
12      17  customer service   61000                   11
13      12             sales   60000                   14
14       8             sales   59000                   15
15      20  customer service   56000                   16
16      21  customer service   55000                   17
17      16  customer service   45000                   18
18      18  customer service   40000                   19
19      15  customer service   38000                   20
20      19  customer service   31000                   21

#### Find the department salary rank

In [9]:
%%sql

SELECT 
    emp_no, 
    department,
    salary,
    RANK() OVER(PARTITION BY department ORDER BY salary DESC) AS dept_salary_rank,
    RANK() OVER(ORDER BY salary DESC) AS overall_salary_rank
FROM employees
ORDER BY department

    emp_no        department  salary  dept_salary_rank  overall_salary_rank
0       17  customer service   61000                 1                   11
1       20  customer service   56000                 2                   16
2       21  customer service   55000                 3                   17
3       16  customer service   45000                 4                   18
4       18  customer service   40000                 5                   19
5       15  customer service   38000                 6                   20
6       19  customer service   31000                 7                   21
7        4       engineering  103000                 1                    2
8        7       engineering   91000                 2                    3
9        6       engineering   89000                 3                    4
10       1       engineering   80000                 4                    5
11       3       engineering   70000                 5                    7
12       2       engineering   69000                 6                    9
13       5       engineering   67000                 7                   10
14      10             sales  159000                 1                    1
15      11             sales   72000                 2                    6
16       9             sales   70000                 3                    7
17      13             sales   61000                 4                   11
18      14             sales   61000                 4                   11
19      12             sales   60000                 6                   14
20       8             sales   59000                 7                   15