#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# ALTER TABLE

## ADD a column
 ```sql
ALTER TABLE table_name
ADD COLUMN column_name VARCHAR(100);
```

In [2]:
%%sql

USE dog_world;

SELECT *
FROM users

   user_id  name  age
0        4  John   19
1        5  Mary    5
2        6  Tony    9

In [3]:
%%sql

ALTER TABLE users
ADD COLUMN user_type VARCHAR(50) NOT NULL;

Empty DataFrame
Columns: []
Index: []

In [4]:
%%sql

INSERT INTO users (name, age, user_type)
VALUES ('liam', 43, 'team')

Empty DataFrame
Columns: []
Index: []

In [5]:
%%sql

SELECT *
FROM users

   user_id  name  age user_type
0        4  John   19
1        5  Mary    5
2        6  Tony    9
3        7  liam   43      team

## DROP a column
 ```sql
ALTER TABLE table_name
DROP COLUMN column_name;
```

In [6]:
%%sql

ALTER TABLE users
DROP COLUMN user_type;

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

SELECT *
FROM users

   user_id  name  age
0        4  John   19
1        5  Mary    5
2        6  Tony    9
3        7  liam   43

## Renaming Tables
 ```sql
RENAME TABLE orig_table_name TO new_table_name
```
#### Other way
 ```sql
ALTER TABLE orig_table_name RENAME TO new_table_name
```

In [8]:
%%sql

ALTER TABLE users RENAME TO existing_users

Empty DataFrame
Columns: []
Index: []

## Renaming Columns
```sql
ALTER TABLE table_name
RENAME COLUMN orig_col_name TO new_col_name
```

In [9]:
%%sql

ALTER TABLE existing_users
RENAME COLUMN name TO existing_names

Empty DataFrame
Columns: []
Index: []

In [10]:
%%sql

SELECT *
FROM existing_users

   user_id existing_names  age
0        4           John   19
1        5           Mary    5
2        6           Tony    9
3        7           liam   43

## Modify Columns
##### By modifying columns we mean that we are actually modifying the Definition of the column
```sql
ALTER TABLE table_name
MODIFY column_name VARCHAR(100)
```

## Changing Columns
#### We can use CHANGE to rename a column AND change its datatype
```sql
ALTER TABLE table_name
CHANGE org_col_name new_col_name VARCHAR(50)
```

In [13]:
%%sql

DESCRIBE existing_users

            Field          Type Null  Key Default           Extra
0         user_id           int   NO  PRI    None  auto_increment
1  existing_names  varchar(100)   NO         None
2             age           int   NO         None

In [14]:
%%sql

ALTER TABLE existing_users
MODIFY existing_names VARCHAR(200) NOT NULL;

Empty DataFrame
Columns: []
Index: []

In [15]:
%%sql

DESCRIBE existing_users

            Field          Type Null  Key Default           Extra
0         user_id           int   NO  PRI    None  auto_increment
1  existing_names  varchar(200)   NO         None
2             age           int   NO         None

#  ALTER TABLE CONSTRAINTS
## ADD or DROP Constraints once the table is created
```sql
ALTER TABLE table_name
ADD CONSTRAINT constraint_name CHECK (expression)
```

#### DROP
```sql
ALTER TABLE table_name
DROP CONSTRAINT constraint_name
```

In [18]:
%%sql

ALTER TABLE houses
ADD CONSTRAINT equal_pricing CHECK (sale_price > purchase_price)

Empty DataFrame
Columns: []
Index: []

In [20]:
%%sql

ALTER TABLE houses
DROP CONSTRAINT equal_pricing

Empty DataFrame
Columns: []
Index: []