#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# ALTER TABLE
```sql
ALTER TABLE table_name
ADD COLUMN column_name VARCHAR(100);
```

In [2]:
%%sql

USE dog_world;

SELECT *
FROM users

   user_id  name  age
0        4  John   19
1        5  Mary    5
2        6  Tony    9

In [3]:
%%sql

ALTER TABLE users
ADD COLUMN user_type VARCHAR(50) NOT NULL;

Empty DataFrame
Columns: []
Index: []

In [4]:
%%sql

INSERT INTO users (name, age, user_type)
VALUES ('liam', 43, 'team')

Empty DataFrame
Columns: []
Index: []

In [5]:
%%sql

SELECT *
FROM users

   user_id  name  age user_type
0        4  John   19
1        5  Mary    5
2        6  Tony    9
3        7  liam   43      team