#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# COUNT

#### Count the number of rows in the books table of the book_shop database

In [3]:
%%sql

USE book_shop;

SELECT 
    COUNT(*)
FROM books

   COUNT(*)
0        19

#### Count the number of author first names

In [4]:
%%sql

SELECT 
    COUNT(author_fname) AS 'author name count'
FROM books

   author name count
0                 19

# COUNT DISTINCT
```sql
SELECT
    COUNT(DISTINCT column_name)
FROM table_name
```

In [6]:
%%sql

SELECT 
    COUNT(DISTINCT author_fname)
FROM books

   COUNT(DISTINCT author_fname)
0                            12

In [7]:
%%sql

SELECT 
    COUNT(DISTINCT released_year)
FROM books

   COUNT(DISTINCT released_year)
0                             16