#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# LIKE
```sql
SELECT
    column1,
    column2
FROM table_name
WHERE column1 LIKE '%search-term%'
```
#### Here % is the wildcard

In [6]:
%%sql

USE book_shop;

SELECT *
FROM books
WHERE author_fname LIKE '%Dave%'
LIMIT 5;

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
1,6,The Circle,Dave,Eggers,2013,26,504
2,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437

# LIKE - UNDERSCORES(_) 
#### Underscore _ represents a character

#### We will use this LIKE _ to find the authors with first name as exactly 4 characters

In [10]:
%%sql

SELECT *
FROM books
WHERE author_fname LIKE '____'

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,2,Norse Mythology,Neil,Gaiman,2016,43,304
1,3,American Gods,Neil,Gaiman,2001,12,465
2,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
3,6,The Circle,Dave,Eggers,2013,26,504
4,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
5,10,Coraline,Neil,Gaiman,2003,100,208
6,14,Cannery Row,John,Steinbeck,1945,95,181

In [12]:
%%sql

SELECT *
FROM books
WHERE author_fname LIKE '_a__'

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
1,6,The Circle,Dave,Eggers,2013,26,504
2,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437

# Escaping Wildcards

#### If we want to search for the book title 10% happier which already has a % in the title then we will have to use the escape character

In [14]:
%%sql

SELECT *
FROM books
WHERE title LIKE '%\%%'

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,17,10% Happier,Dan,Harris,2014,29,256

#### In case the name has a _

In [18]:
%%sql

SELECT *
FROM books
WHERE title LIKE '%\_%'

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,18,fake_book,Freida,Harris,2001,287,428