#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# ORDER BY

```sql
SELECT 
    column1,
    column2,
    column3
FROM table_name
WHERE condition
GROUP BY column2
ORDER BY column1
```
#### ASC and DESC order can be controlled but ASC is by default

In [7]:
%%sql

USE book_shop;

SELECT 
    book_id,
    author_fname,
    author_lname
FROM books
ORDER BY author_lname DESC

    book_id author_fname    author_lname
0        14         John       Steinbeck
1         8        Patti           Smith
2        19       George        Saunders
3         1       Jhumpa          Lahiri
4         4       Jhumpa          Lahiri
5        17          Dan          Harris
6        18       Freida          Harris
7         2         Neil          Gaiman
8         3         Neil          Gaiman
9        10         Neil          Gaiman
10       15        David  Foster Wallace
11       16        David  Foster Wallace
12        5         Dave          Eggers
13        6         Dave          Eggers
14        9         Dave          Eggers
15       13          Don         DeLillo
16        7      Michael          Chabon
17       11      Raymond          Carver
18       12      Raymond          Carver

In [9]:
%%sql

SELECT
    book_id,
    author_fname,
    author_lname
FROM books
ORDER BY book_id DESC

    book_id author_fname    author_lname
0        19       George        Saunders
1        18       Freida          Harris
2        17          Dan          Harris
3        16        David  Foster Wallace
4        15        David  Foster Wallace
5        14         John       Steinbeck
6        13          Don         DeLillo
7        12      Raymond          Carver
8        11      Raymond          Carver
9        10         Neil          Gaiman
10        9         Dave          Eggers
11        8        Patti           Smith
12        7      Michael          Chabon
13        6         Dave          Eggers
14        5         Dave          Eggers
15        4       Jhumpa          Lahiri
16        3         Neil          Gaiman
17        2         Neil          Gaiman
18        1       Jhumpa          Lahiri

In [10]:
%%sql

SELECT
    book_id,
    author_fname,
    author_lname,
    pages
FROM books
ORDER BY pages DESC

    book_id author_fname    author_lname  pages
0         7      Michael          Chabon    634
1        12      Raymond          Carver    526
2         6         Dave          Eggers    504
3         3         Neil          Gaiman    465
4         9         Dave          Eggers    437
5        18       Freida          Harris    428
6        19       George        Saunders    367
7         5         Dave          Eggers    352
8        16        David  Foster Wallace    343
9        15        David  Foster Wallace    329
10       13          Don         DeLillo    320
11        2         Neil          Gaiman    304
12        8        Patti           Smith    304
13        1       Jhumpa          Lahiri    291
14       17          Dan          Harris    256
15       10         Neil          Gaiman    208
16        4       Jhumpa          Lahiri    198
17       14         John       Steinbeck    181
18       11      Raymond          Carver    176

In [11]:
%%sql

SELECT
    book_id,
    author_fname,
    author_lname,
    released_year
FROM books
ORDER BY released_year DESC

    book_id author_fname    author_lname  released_year
0        19       George        Saunders           2017
1         2         Neil          Gaiman           2016
2        17          Dan          Harris           2014
3         6         Dave          Eggers           2013
4         5         Dave          Eggers           2012
5         8        Patti           Smith           2010
6        16        David  Foster Wallace           2005
7        15        David  Foster Wallace           2004
8         1       Jhumpa          Lahiri           2003
9        10         Neil          Gaiman           2003
10        3         Neil          Gaiman           2001
11        9         Dave          Eggers           2001
12       18       Freida          Harris           2001
13        7      Michael          Chabon           2000
14        4       Jhumpa          Lahiri           1996
15       12      Raymond          Carver           1989
16       13          Don         DeLillo           1985
17       11      Raymond          Carver           1981
18       14         John       Steinbeck           1945

# ORDER BY - shorthand syntax 
```sql
SELECT 
    column1,
    column2,
    column3
FROM table_name
WHERE condition
ORDER BY 2
```
#### Here 2 is basically the second column in the SELECT statement

In [14]:
%%sql

SELECT 
    title,
    author_fname, 
    author_lname
FROM books
ORDER BY 2;

,title,author_fname,author_lname
0,10% Happier,Dan,Harris
1,A Hologram for the King: A Novel,Dave,Eggers
2,The Circle,Dave,Eggers
3,A Heartbreaking Work of Staggering Genius,Dave,Eggers
4,Oblivion: Stories,David,Foster Wallace
5,Consider the Lobster,David,Foster Wallace
6,White Noise,Don,DeLillo
7,fake_book,Freida,Harris
8,Lincoln In The Bardo,George,Saunders
9,The Namesake,Jhumpa,Lahiri
10,Interpreter of Maladies,Jhumpa,Lahiri
11,Cannery Row,John,Steinbeck
12,The Amazing Adventures of Kavalier & Clay,Michael,Chabon
13,Norse Mythology,Neil,Gaiman
14,American Gods,Neil,Gaiman
15,Coraline,Neil,Gaiman
16,Just Kids,Patti,Smith
17,What We Talk About When We Talk About Love: St...,Raymond,Carver
18,Where I'm Calling From: Selected Stories,Raymond,Carver

# MULTI COLUMN SORT BY
```sql
SELECT 
    column1,
    column2,
    column3
FROM table_name
WHERE condition
GROUP BY column2
ORDER BY column1, column2
```
#### So in such cases the ORDER BT takes place for the first column and then moves to the ORDER BY for the next column

In [16]:
%%sql

SELECT 
    book_id,
    title,
    author_fname,
    released_year
FROM books
ORDER BY released_year, book_id

,book_id,title,author_fname,released_year
0,14,Cannery Row,John,1945
1,11,What We Talk About When We Talk About Love: St...,Raymond,1981
2,13,White Noise,Don,1985
3,12,Where I'm Calling From: Selected Stories,Raymond,1989
4,4,Interpreter of Maladies,Jhumpa,1996
5,7,The Amazing Adventures of Kavalier & Clay,Michael,2000
6,3,American Gods,Neil,2001
7,9,A Heartbreaking Work of Staggering Genius,Dave,2001
8,18,fake_book,Freida,2001
9,1,The Namesake,Jhumpa,2003
10,10,Coraline,Neil,2003
11,15,Oblivion: Stories,David,2004
12,16,Consider the Lobster,David,2005
13,8,Just Kids,Patti,2010
14,5,A Hologram for the King: A Novel,Dave,2012
15,6,The Circle,Dave,2013
16,17,10% Happier,Dan,2014
17,2,Norse Mythology,Neil,2016
18,19,Lincoln In The Bardo,George,2017

# We can do ORDER BY also via alias

In [17]:
%%sql

SELECT 
    CONCAT(author_fname, ' ', author_lname) AS author
FROM books
ORDER BY author

                  author
0             Dan Harris
1            Dave Eggers
2            Dave Eggers
3            Dave Eggers
4   David Foster Wallace
5   David Foster Wallace
6            Don DeLillo
7          Freida Harris
8        George Saunders
9          Jhumpa Lahiri
10         Jhumpa Lahiri
11        John Steinbeck
12        Michael Chabon
13           Neil Gaiman
14           Neil Gaiman
15           Neil Gaiman
16           Patti Smith
17        Raymond Carver
18        Raymond Carver