#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Not Equal (!=)

In [3]:
%%sql

USE book_shop;

SELECT *
FROM books
WHERE released_year != 2003

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,2,Norse Mythology,Neil,Gaiman,2016,43,304
1,3,American Gods,Neil,Gaiman,2001,12,465
2,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
3,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
4,6,The Circle,Dave,Eggers,2013,26,504
5,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
6,8,Just Kids,Patti,Smith,2010,55,304
7,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
8,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
9,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526
10,13,White Noise,Don,DeLillo,1985,49,320
11,14,Cannery Row,John,Steinbeck,1945,95,181
12,15,Oblivion: Stories,David,Foster Wallace,2004,172,329
13,16,Consider the Lobster,David,Foster Wallace,2005,92,343
14,17,10% Happier,Dan,Harris,2014,29,256
15,18,fake_book,Freida,Harris,2001,287,428
16,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

In [4]:
%%sql

SELECT *
FROM books
WHERE author_lname != 'Harris'

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304
2,3,American Gods,Neil,Gaiman,2001,12,465
3,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
4,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
5,6,The Circle,Dave,Eggers,2013,26,504
6,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
7,8,Just Kids,Patti,Smith,2010,55,304
8,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
9,10,Coraline,Neil,Gaiman,2003,100,208
10,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
11,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526
12,13,White Noise,Don,DeLillo,1985,49,320
13,14,Cannery Row,John,Steinbeck,1945,95,181
14,15,Oblivion: Stories,David,Foster Wallace,2004,172,329
15,16,Consider the Lobster,David,Foster Wallace,2005,92,343
16,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

# NOT LIKE

##### I want to find all the books that do not have a space in their title

In [7]:
%%sql

SELECT
    title
FROM books
WHERE title NOT LIKE '% %'

       title
0   Coraline
1  fake_book

In [9]:
%%sql

SELECT 
    author_fname
FROM books
WHERE author_fname NOT LIKE '%Da%'

   author_fname
0        Jhumpa
1          Neil
2          Neil
3        Jhumpa
4       Michael
5         Patti
6          Neil
7       Raymond
8       Raymond
9           Don
10         John
11       George

# Greater than (>)

In [10]:
%%sql

SELECT *
FROM books
WHERE released_year > 2010

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,2,Norse Mythology,Neil,Gaiman,2016,43,304
1,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
2,6,The Circle,Dave,Eggers,2013,26,504
3,17,10% Happier,Dan,Harris,2014,29,256
4,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

# Less Than or Equal To

In [12]:
%%sql

SELECT *
FROM books
WHERE released_year <= 2000

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
1,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
2,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
3,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526
4,13,White Noise,Don,DeLillo,1985,49,320
5,14,Cannery Row,John,Steinbeck,1945,95,181

# Logical AND (&&)

#### Find all the books written by Dave and published after 2010

In [16]:
%%sql

SELECT *
FROM books
WHERE
    author_fname = 'Dave' &&
    released_year > 2010

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
1,6,The Circle,Dave,Eggers,2013,26,504

#### Find the books that have a title greater than 15 and has many pages than all

In [20]:
%%sql

SELECT *
FROM books
WHERE
    CHAR_LENGTH(title) > 15 AND
    pages > 500

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
1,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526

# Logical OR

In [21]:
%%sql

SELECT *
FROM books
WHERE
    author_fname = 'Dave' OR
    released_year > 2010

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,2,Norse Mythology,Neil,Gaiman,2016,43,304
1,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
2,6,The Circle,Dave,Eggers,2013,26,504
3,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
4,17,10% Happier,Dan,Harris,2014,29,256
5,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

# BETWEEN

#### Get all the books published between 2004 and 2015

In [24]:
%%sql

SELECT *
FROM books
WHERE released_year BETWEEN 2004 AND 2015

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
1,6,The Circle,Dave,Eggers,2013,26,504
2,8,Just Kids,Patti,Smith,2010,55,304
3,15,Oblivion: Stories,David,Foster Wallace,2004,172,329
4,16,Consider the Lobster,David,Foster Wallace,2005,92,343
5,17,10% Happier,Dan,Harris,2014,29,256

# NOT BETWEEN

In [25]:
%%sql

SELECT *
FROM books
WHERE released_year NOT BETWEEN 2004 AND 2015

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304
2,3,American Gods,Neil,Gaiman,2001,12,465
3,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
4,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
5,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
6,10,Coraline,Neil,Gaiman,2003,100,208
7,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
8,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526
9,13,White Noise,Don,DeLillo,1985,49,320
10,14,Cannery Row,John,Steinbeck,1945,95,181
11,18,fake_book,Freida,Harris,2001,287,428
12,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

# Comparing Dates

In [28]:
%%sql

USE dog_world;

SELECT *
FROM people
WHERE birth_date < '2005-01-01'

    name  birth_date      birth_time             birthdt
0   Matt  2001-12-25 0 days 11:00:00 2001-12-25 11:00:00
1   Lulu  2003-01-20 0 days 23:59:10 2003-01-20 23:59:10
2  Peter  2001-11-28 0 days 11:30:20 2001-11-28 11:30:20

In [29]:
%%sql

SELECT *
FROM people
WHERE YEAR(birth_date) < 2005

    name  birth_date      birth_time             birthdt
0   Matt  2001-12-25 0 days 11:00:00 2001-12-25 11:00:00
1   Lulu  2003-01-20 0 days 23:59:10 2003-01-20 23:59:10
2  Peter  2001-11-28 0 days 11:30:20 2001-11-28 11:30:20

# CAST

In [30]:
%%sql

SELECT 
    CAST('09:00:00' AS TIME)

  CAST('09:00:00' AS TIME)
0          0 days 09:00:00

In [34]:
%%sql

SELECT *
FROM people
WHERE birth_time 
    BETWEEN 
        CAST('10:00:00' AS TIME) AND 
        CAST('12:00:00' AS TIME)

    name  birth_date      birth_time             birthdt
0   Matt  2001-12-25 0 days 11:00:00 2001-12-25 11:00:00
1    Ben  2010-10-02 0 days 11:15:10 2010-10-02 11:15:10
2  Peter  2001-11-28 0 days 11:30:20 2001-11-28 11:30:20

# IN Operator

In [36]:
%%sql

USE book_shop;

SELECT *
FROM books
WHERE author_lname IN ('Carver', 'Lahiri', 'Smith')

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
2,8,Just Kids,Patti,Smith,2010,55,304
3,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
4,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526

# NOT IN Operator

In [39]:
%%sql

USE book_shop;

SELECT *
FROM books
WHERE author_lname NOT IN ('Carver', 'Lahiri', 'Smith', 'Harris', 'Dave')

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,2,Norse Mythology,Neil,Gaiman,2016,43,304
1,3,American Gods,Neil,Gaiman,2001,12,465
2,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
3,6,The Circle,Dave,Eggers,2013,26,504
4,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
5,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
6,10,Coraline,Neil,Gaiman,2003,100,208
7,13,White Noise,Don,DeLillo,1985,49,320
8,14,Cannery Row,John,Steinbeck,1945,95,181
9,15,Oblivion: Stories,David,Foster Wallace,2004,172,329
10,16,Consider the Lobster,David,Foster Wallace,2005,92,343
11,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

In [43]:
%%sql

SELECT *
FROM books
WHERE released_year % 2 = 0

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,2,Norse Mythology,Neil,Gaiman,2016,43,304
1,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
2,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
3,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
4,8,Just Kids,Patti,Smith,2010,55,304
5,15,Oblivion: Stories,David,Foster Wallace,2004,172,329
6,17,10% Happier,Dan,Harris,2014,29,256